KristianWEB/fakebooker-frontend

.travis.yml, README.md, package.json
1) Changed .travis.yml to use yarn instead of npm.
2) Added `travis build badge` in `README.md`
3) Added live demo link in `README.md`
=> Changed npm to yarn in .travis.yml

src/App/components/LandingPage/LandingPage.css, src/App/components/LandingPage/LandingPage.jsx
=> Updated Landing

src/App/components/LandingPage/LandingPage.css
=> centered the logo

.eslintignore, .eslintrc.js, package.json, src/App/App.jsx, src/App/components/LandingPage/LandingPage.jsx, src/App/components/NotFoundPage/NotFoundPage.jsx, src/App/components/routing/PrivateRoute.jsx, src/App/components/routing/Routes.jsx, yarn.lock
=> Added routing

.eslintrc.js, .prettierrc
1) Added a rule to `.eslintrc` so that eslint will throw errors if `prettier is also not happy`.
2) Added `.prettierrc` file where we can setup prettier rules. For now single quotes are set to false assuming that we are going with double quotes for this project.
=> added .prettierrc file

src/App/components/ProfilePage/ProfilePage.jsx, src/App/components/routing/Routes.jsx
1) Just created a file `components/ProfilePage/ProfilePag.jsx` which for now just displays `Profile Page Works`. 
2) Also added a route `<Route exact path="/profile" component={ProfilePage} />`
=> created profile page component

src/App/components/LandingPage/LandingPage.jsx, src/App/context/auth/AuthProvider.jsx
I have added a new `username` field on the signUp tab. Also I've updated the POST Request that is sent to the backend with the new signUp parameters.
=> Username implementation

src/App/components/Navbar/Navbar.jsx, src/App/components/ProfilePage/ProfilePage.jsx, src/App/components/ProfilePage/components/Post.jsx, src/App/components/routing/Routes.jsx
* Connected Navbar, profileHeader, Post Components into the ProfilePage wrapper component.
* Display user's username on Navbar just for reference aswell.
* Removed hashed router and replaced it with BrowserRouter so there is no hash in the url anymore.
=> connected profilePage components and removed hashed router

src/App/components/ProfilePage/ProfilePage.jsx, src/App/components/ProfilePage/components/MockupForm.jsx
* Added mockup form for the posting functionality
=> added mockup form

src/App/components/LandingPage/LandingPage.jsx, src/App/components/LandingPage/LoginForm.jsx, src/App/components/LandingPage/RegisterForm.jsx
Merge the feature/landing-strucure branch on master repo after merging this pr.
=> Landing page separation of concerns

src/App/components/LandingPage/LandingPage.styles.js, src/App/components/LandingPage/RegisterForm.jsx
Implemented Password validation and it's rules to pass it are:
* Password should have atleast 1 uppercase letter.
* Password should have atleast 1 number.
* Password should be atleast 8 characters.
I've also added a small grey text under password input just for reference ( FOR NOW ).
Closes #56
=> added register password validation

src/App/components/ProfilePage/components/Posting/CreatePost.jsx, src/App/components/ProfilePage/components/Posting/Post.jsx
* I'm simply now calling getPosts action after the user creates a post using addPost action.
* Closes #90
=>  display newly added post by user

src/App/components/ProfilePage/ProfilePage.jsx, src/App/components/ProfilePage/components/AboutNew.jsx, src/App/components/ProfilePage/components/AboutNew.styles.js
* Implemented the new design of our about component
=> implemented new about component

src/components/Post/Post.jsx, src/components/Post/Post.styles.js, src/utils/graphql/queries.js
=> implemented post deleting functionality

src/components/Navbar/Navbar.jsx, src/components/Post/CreatePostDefault.jsx, src/components/Post/CreatePostDefault.styles.js, src/components/Post/Post.stories.js
* Fixes NavBar icons
* Implemented Create Post default state
=> implemented create post default state & fixed navbar icons

src/components/Post/CreatePostNew.jsx, src/components/Post/CreatePostNew.styles.js, src/components/Post/Post.stories.js
* Implemented active state create post
* Now we can override styles really easy [using this article](https://github.com/styled-components/styled-components/issues/1816)
=> createpost active state implemented

src/App.css, src/components/About/About.styles.js, src/components/About/AboutForm.styles.js, src/components/Comment/Comment.jsx, src/components/Comment/Comment.stories.js, src/components/Comment/Comment.styles.js, src/components/Comment/CreateComment.jsx, src/components/Comment/CreateComment.styles.js, src/components/Navbar/Navbar.styles.js, src/components/Post/CreatePostNew.styles.js, src/components/ProfileHeader/ProfileHeader.styles.js
=> comment implemented

src/components/About/About.styles.js, src/components/Navbar/Navbar.jsx, src/components/Post/CreatePostDefault.jsx, src/components/Post/CreatePostDefault.styles.js, src/components/Post/CreatePostNew.jsx, src/components/Post/Post.jsx, src/components/Post/Post.styles.js, src/components/ProfileHeader/ProfileHeader.jsx, src/components/ProfileHeader/ProfileHeader.styles.js, src/pages/ProfilePage/ProfilePage.jsx, src/pages/ProfilePage/ProfilePage.styles.js
=> glued the profile page

src/components/About/About.jsx, src/components/About/AboutForm.jsx, src/components/About/AboutForm.styles.js, src/components/Post/CreatePostDefault.jsx
=> about form modal implemented

src/App.jsx, src/components/Navbar/Navbar.styles.js, src/components/ProfileHeader/ProfileHeader.styles.js, src/globalStyles/index.js
On issue #150 
* Normalized styles, 1 rem = 10px
=> normalized styles, 1rem = 10px

antd-customizations.js, config-overrides.js, src/components/About/About.styles.js, src/components/LoginForm/LoginForm.jsx, src/components/LoginForm/LoginForm.styles.js, src/components/RegisterForm/RegisterForm.jsx, src/components/RegisterForm/RegisterForm.styles.js, src/globalStyles/index.js, src/pages/ProfilePage/ProfilePage.styles.js, src/pages/RegisterPage/AuthPage.jsx, src/pages/RegisterPage/AuthPage.styles.js, src/routes/PrivateRoute.jsx, src/routes/Routes.jsx, src/utils/graphql/queries.js
=> implemented login form & fixed profile page

src/components/ProfileHeader/ProfileHeader.jsx, src/pages/PhotosPage/PhotosPage.jsx, src/pages/PhotosPage/PhotosPage.styles.js, src/routes/Routes.jsx, src/utils/queries.js
=> Photos section on profile implemented

src/ApolloProvider.jsx, src/components/Friend/Friend.jsx, src/components/Friend/Friend.styles.js, src/components/ProfileHeader/ProfileHeader.jsx, src/pages/AboutPage/AboutOverview.jsx, src/pages/FriendsPage/FriendsPage.jsx, src/pages/FriendsPage/FriendsPage.styles.js, src/routes/Routes.jsx, src/routes/layouts/AboutLayout.jsx, src/utils/queries.js
=> Friends section: Profile Implemented

src/pages/AboutPage/AboutContactAndBasicInfo.jsx, src/pages/AboutPage/AboutOverview.jsx, src/pages/AboutPage/AboutWorkAndEducation.jsx, src/pages/FriendsPage/FriendsPage.jsx, src/pages/NewsfeedPage/NewsfeedPage.jsx, src/pages/ProfilePage/ProfilePage.jsx, src/utils/queries.js
=> loadUserFromDB replaced by loadUser newToken: true

src/globalStyles/index.js, src/pages/AuthPage/AuthPage.styles.js, src/pages/NewsfeedPage/NewsfeedPage.styles.js, src/pages/ProfilePage/ProfilePage.styles.js
=> white gap fixed

src/ApolloProvider.jsx, src/components/Comment/CreateComment.jsx, src/components/Comment/CreateComment.styles.js, src/components/Image/Image.jsx, src/components/Message/Message.jsx, src/components/Message/SingleChat.jsx, src/components/Message/SingleChat.styles.js, src/components/Notification/Notification.jsx, src/components/Post/CreatePostActive.jsx, src/components/Post/CreatePostActive.styles.js, src/pages/AboutPage/AboutContactAndBasicInfo.jsx, src/pages/AboutPage/AboutContactAndBasicInfo.styles.js, src/pages/AboutPage/AboutWorkAndEducation.jsx
=> input validation implemented & react hook form applied to all forms

src/components/Message/MessageList.styles.js, src/components/Message/SingleChat.jsx, src/components/Message/SingleChat.styles.js, src/components/Notification/NotificationList.styles.js
* Close #233 
* Close #215 
* Close #216
=> messenger & singlechat & notifications tab

src/routes/PrivateRoute.jsx, src/routes/ProfileRoute.jsx, src/utils/queries.js
=> implemented #251 feature

src/App.jsx, src/components/About/About.styles.js, src/components/Notification/Notification.jsx, src/components/Notification/Notification.styles.js, src/components/Post/CreatePostDefault.styles.js, src/components/Post/Post.styles.js, src/components/ProfileHeader/ProfileHeader.styles.js, src/globalStyles/index.js, src/pages/AboutPage/AboutContactAndBasicInfo.styles.js, src/pages/AboutPage/AboutOverview.styles.js, src/pages/AboutPage/AboutWorkAndEducation.styles.js, src/pages/FriendsPage/FriendsPage.styles.js, src/pages/NewsfeedPage/NewsfeedPage.jsx, src/pages/NewsfeedPage/NewsfeedPage.styles.js, src/pages/PhotosPage/PhotosPage.styles.js, src/pages/ProfilePage/ProfilePage.styles.js, src/pages/SinglePostPage/SinglePostPage.jsx, src/pages/SinglePostPage/SinglePostPage.styles.js, src/routes/ProfileRoute.jsx, src/routes/Routes.jsx, src/utils/queries.js
=> notification refactored, other stuff

src/components/About/About.styles.js, src/pages/PhotosPage/PhotosPage.styles.js, src/pages/ProfilePage/ProfilePage.jsx, src/pages/ProfilePage/ProfilePage.styles.js
=> #230 fixed

src/components/Comment/Comment.jsx, src/components/Comment/Comment.styles.js, src/components/Comment/CreateComment.jsx, src/components/Post/Post.jsx, src/components/Post/Post.styles.js, src/pages/ProfilePage/ProfilePage.styles.js, src/utils/queries.js
=> post creator refactored + newfeedpage comments

src/components/Post/CreatePostActive.jsx, src/components/Post/CreatePostDefault.jsx, src/components/Post/CreatePostDefault.styles.js, src/pages/NewsfeedPage/NewsfeedPage.jsx, src/pages/NewsfeedPage/NewsfeedPage.styles.js
=> newsfeed create post

src/components/Image/ChangeAvatarPhoto.jsx, src/components/Image/ChangeCoverPhoto.jsx, src/components/Image/Image.jsx
Cloudinary preset "kristian" fixed value has been entered, it must be changed dynamically from .env
=> Cloudinary preset is set to .env

src/components/Post/Post.jsx, src/components/Post/Post.styles.js
Removed LikesWrapper and modified LikeButton.
=> Fix: [Main page] Notification spamming using the like button

src/components/Comment/CreateComment.jsx
Fixed the issue where you can spam comment a post while its loading.
=> Fix: Comment spamming

src/pages/ProfilePage/ProfilePage.jsx
=> post skeletons fixed
